name: Generate allure reports
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  get-Allure-History:
    name: Get Allure history
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

  marketPlaceAllure:  
    name: Test marketplace action
    runs-on: ubuntu-latest
    steps:
      - uses: simple-elf/allure-report-action@master
        if: always()
        id: get-Allure-History
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
  
  publish-on-github-page:
      name: Deploy report to Github Pages
      if: always()
      runs-on: ubuntu-latest
      steps:
       - uses: peaceiris/actions-gh-pages@v2
         env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN_PRV }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
